"""Initial migration

Revision ID: 15c00b803ca6
Revises: 
Create Date: 2026-03-20 15:23:51.229401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '15c00b803ca6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.Enum('DONOR', 'RECEPTOR', name='rolusuario'), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=False),
    sa.Column('telefono', sa.String(length=50), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('lotes_alimentos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('donante_id', sa.Uuid(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('cantidad', sa.String(length=100), nullable=False),
    sa.Column('categoria', sa.Enum('PANADERIA', 'FRUTAS', 'LACTEOS', 'VEGETALES', 'OTROS', name='categoriaalimento'), nullable=False),
    sa.Column('estado', sa.Enum('ACTIVO', 'RESERVADO', 'COMPLETADO', 'CANCELADO', name='estadolote'), nullable=False),
    sa.Column('imagen_url', sa.String(length=500), nullable=True),
    sa.Column('ubicacion', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('fecha_publicacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_caducidad', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['donante_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reservas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('lote_id', sa.Uuid(), nullable=False),
    sa.Column('receptor_id', sa.Uuid(), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'RECOGIDO', 'VENCIDO', name='estadoreserva'), nullable=False),
    sa.Column('codigo_qr_token', sa.String(length=255), nullable=False),
    sa.Column('fecha_reserva', sa.DateTime(), nullable=False),
    sa.Column('fecha_limite_recogida', sa.DateTime(), nullable=False),
    sa.Column('fecha_completada', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes_alimentos.id'], ),
    sa.ForeignKeyConstraint(['receptor_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_qr_token'),
    sa.UniqueConstraint('lote_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservas')
    op.drop_table('lotes_alimentos')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
